export interface Instructor {
  id: string;
  name: string;
  role: string;
  achievement: string;
  imageSrc: string;
  category: Category;
}

export const CATEGORIES = [
  "AI",
  "Product",
  "Engineering",
  "Design",
  "Leadership",
  "Marketing",
] as const;

export type Category = (typeof CATEGORIES)[number];

export const INSTRUCTORS_DATA: Instructor[] = [
  // ==========================================
  // 1. AI (10 Items)
  // ==========================================
  {
    id: "ai-1",
    name: "Pietro Montaldo",
    role: "Founder & Growth Operator",
    achievement: "Scaled $0→$1M in 9 months",
    imageSrc: "https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg",
    category: "AI",
  },
  {
    id: "ai-2",
    name: "Dr. Aris Thorne",
    role: "LLM Research Scientist",
    achievement: "Author of 14 NeurIPS papers",
    imageSrc: "https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg",
    category: "AI",
  },
  {
    id: "ai-3",
    name: "Mei-Ling Zhou",
    role: "Computer Vision Lead",
    achievement: "Shipped edge models to 20M devices",
    imageSrc: "https://images.pexels.com/photos/3756679/pexels-photo-3756679.jpeg",
    category: "AI",
  },
  {
    id: "ai-4",
    name: "Julian Rivera",
    role: "MLOps Platform Architect",
    achievement: "Cut GPU training costs by 65%",
    imageSrc: "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg",
    category: "AI",
  },
  {
    id: "ai-5",
    name: "Kavita Rao",
    role: "Generative AI Strategist",
    achievement: "Trained 50k+ engineers in prompt engineering",
    imageSrc: "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg",
    category: "AI",
  },
  {
    id: "ai-6",
    name: "Alexandre Dupont",
    role: "NLP Engineering Director",
    achievement: "Engineered multilingual agent pipeline",
    imageSrc: "https://images.pexels.com/photos/1516680/pexels-photo-1516680.jpeg",
    category: "AI",
  },
  {
    id: "ai-7",
    name: "Amina Al-Mansoor",
    role: "Autonomous Systems Researcher",
    achievement: "Patented zero-shot vision framework",
    imageSrc: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg",
    category: "AI",
  },
  {
    id: "ai-8",
    name: "Devon Clark",
    role: "AI Alignment Specialist",
    achievement: "Ex-DeepMind Safety Contributor",
    imageSrc: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg",
    category: "AI",
  },
  {
    id: "ai-9",
    name: "Siddharth Verma",
    role: "Foundational Model Engineer",
    achievement: "Built 7B parameter open-source LLM",
    imageSrc: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg",
    category: "AI",
  },
  {
    id: "ai-10",
    name: "Chloe Dupont",
    role: "Applied Deep Learning Lead",
    achievement: "Delivered medical diagnostics AI",
    imageSrc: "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg",
    category: "AI",
  },

  // ==========================================
  // 2. PRODUCT (10 Items)
  // ==========================================
  {
    id: "prod-1",
    name: "Marcus Vance",
    role: "VP of Product",
    achievement: "Led 50+ Product Launches",
    imageSrc: "https://images.pexels.com/photos/3785079/pexels-photo-3785079.jpeg",
    category: "Product",
  },
  {
    id: "prod-2",
    name: "Rachel Steinberg",
    role: "Principal Product Manager",
    achievement: "Scaled Uber Core Ride flow to $2B GMV",
    imageSrc: "https://images.pexels.com/photos/762020/pexels-photo-762020.jpeg",
    category: "Product",
  },
  {
    id: "prod-3",
    name: "Kenji Sato",
    role: "Head of Product Strategy",
    achievement: "Spearheaded B2B pivot from $5M to $80M",
    imageSrc: "https://images.pexels.com/photos/2182977/pexels-photo-2182977.jpeg",
    category: "Product",
  },
  {
    id: "prod-4",
    name: "Tanya Morrison",
    role: "Growth Product Director",
    achievement: "Boosted product activation by 42%",
    imageSrc: "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg",
    category: "Product",
  },
  {
    id: "prod-5",
    name: "Lucas Romero",
    role: "Fintech Product Lead",
    achievement: "Launched cross-border payments in 18 countries",
    imageSrc: "https://images.pexels.com/photos/837358/pexels-photo-837358.jpeg",
    category: "Product",
  },
  {
    id: "prod-6",
    name: "Ananya Deshmukh",
    role: "Group Product Manager",
    achievement: "Built self-serve SaaS funnel from scratch",
    imageSrc: "https://images.pexels.com/photos/1587009/pexels-photo-1587009.jpeg",
    category: "Product",
  },
  {
    id: "prod-7",
    name: "Oliver Finch",
    role: "Product Operations Lead",
    achievement: "Shortened launch cycle time by 4 weeks",
    imageSrc: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg",
    category: "Product",
  },
  {
    id: "prod-8",
    name: "Hanna Lindqvist",
    role: "Enterprise Product Architect",
    achievement: "Scaled enterprise tier retention to 98%",
    imageSrc: "https://images.pexels.com/photos/1858175/pexels-photo-1858175.jpeg",
    category: "Product",
  },
  {
    id: "prod-9",
    name: "Darius Washington",
    role: "Senior Director of PM",
    achievement: "Mentored 100+ APMs into senior leads",
    imageSrc: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg",
    category: "Product",
  },
  {
    id: "prod-10",
    name: "Sofia Giraldo",
    role: "Consumer PM Specialist",
    achievement: "Grew mobile DAUs from 500K to 4.2M",
    imageSrc: "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg",
    category: "Product",
  },

  // ==========================================
  // 3. ENGINEERING (10 Items)
  // ==========================================
  {
    id: "eng-1",
    name: "Ravi Gahire",
    role: "MERN Stack Developer",
    achievement: "Scaled 0 to 1M users",
    imageSrc: "https://images.pexels.com/photos/30976004/pexels-photo-30976004.jpeg",
    category: "Engineering",
  },
  {
    id: "eng-2",
    name: "Liam O'Connor",
    role: "Distributed Systems Architect",
    achievement: "Achieved 99.999% uptime on high-traffic fintech",
    imageSrc: "https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg",
    category: "Engineering",
  },
  {
    id: "eng-3",
    name: "Chioma Okoye",
    role: "Senior Cloud Engineer",
    achievement: "Terraform automation across 1,200 microservices",
    imageSrc: "https://images.pexels.com/photos/1181519/pexels-photo-1181519.jpeg",
    category: "Engineering",
  },
  {
    id: "eng-4",
    name: "Viktor Petrov",
    role: "Staff Backend Engineer",
    achievement: "Optimized DB queries reducing latency by 80%",
    imageSrc: "https://images.pexels.com/photos/842567/pexels-photo-842567.jpeg",
    category: "Engineering",
  },
  {
    id: "eng-5",
    name: "Evelyn Reed",
    role: "Principal Frontend Engineer",
    achievement: "Core contributor to major open-source web frameworks",
    imageSrc: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg",
    category: "Engineering",
  },
  {
    id: "eng-6",
    name: "Carlos Mendoza",
    role: "Mobile Engineering Lead",
    achievement: "Engineered React Native app with 10M+ downloads",
    imageSrc: "https://images.pexels.com/photos/1040880/pexels-photo-1040880.jpeg",
    category: "Engineering",
  },
  {
    id: "eng-7",
    name: "Nandita Iyer",
    role: "Application Security Architect",
    achievement: "Designed zero-trust security infrastructure",
    imageSrc: "https://images.pexels.com/photos/1820559/pexels-photo-1820559.jpeg",
    category: "Engineering",
  },
  {
    id: "eng-8",
    name: "Jonas Keller",
    role: "DevOps & Platform Lead",
    achievement: "Reduced deployment cycles from days to minutes",
    imageSrc: "https://images.pexels.com/photos/1680172/pexels-photo-1680172.jpeg",
    category: "Engineering",
  },
  {
    id: "eng-9",
    name: "Fatima Zahra",
    role: "Full-Stack Tech Lead",
    achievement: "Architected multi-tenant SaaS frontend pipeline",
    imageSrc: "https://images.pexels.com/photos/1239288/pexels-photo-1239288.jpeg",
    category: "Engineering",
  },
  {
    id: "eng-10",
    name: "Tyler Brooks",
    role: "Rust & Systems Programmer",
    achievement: "Authored low-latency trading engine core",
    imageSrc: "https://images.pexels.com/photos/2269872/pexels-photo-2269872.jpeg",
    category: "Engineering",
  },

  // ==========================================
  // 4. DESIGN (10 Items)
  // ==========================================
  {
    id: "des-1",
    name: "Sarah Chen",
    role: "Principal Product Designer",
    achievement: "Ex-Stripe Design Lead",
    imageSrc: "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg",
    category: "Design",
  },
  {
    id: "des-2",
    name: "Mateo Silva",
    role: "Head of Design Systems",
    achievement: "Unified 40+ products under one global tokens system",
    imageSrc: "https://images.pexels.com/photos/2379005/pexels-photo-2379005.jpeg",
    category: "Design",
  },
  {
    id: "des-3",
    name: "Zoe Kravitz-Miller",
    role: "Staff UX Researcher",
    achievement: "Spearheaded user research for 80M global accounts",
    imageSrc: "https://images.pexels.com/photos/3777943/pexels-photo-3777943.jpeg",
    category: "Design",
  },
  {
    id: "des-4",
    name: "Lars Van Der Beek",
    role: "Creative Director",
    achievement: "3x Cannes Lions Winner for Digital Craft",
    imageSrc: "https://images.pexels.com/photos/1300402/pexels-photo-1300402.jpeg",
    category: "Design",
  },
  {
    id: "des-5",
    name: "Aarti Patel",
    role: "Senior UI/Interaction Designer",
    achievement: "Created micro-interactions seen by 100M+ users",
    imageSrc: "https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg",
    category: "Design",
  },
  {
    id: "des-6",
    name: "Dominic Wade",
    role: "Brand & Visual Identity Lead",
    achievement: "Led global rebrand for Fortune 500 SaaS",
    imageSrc: "https://images.pexels.com/photos/2182974/pexels-photo-2182974.jpeg",
    category: "Design",
  },
  {
    id: "des-7",
    name: "Yuki Tanaka",
    role: "Spatial & 3D UI Designer",
    achievement: "Pioneered mixed-reality onboarding mechanics",
    imageSrc: "https://images.pexels.com/photos/157661/pexels-photo-157661.jpeg",
    category: "Design",
  },
  {
    id: "des-8",
    name: "Camila Fernandez",
    role: "Accessibility & UX Specialist",
    achievement: "Audited and certified WCAG AAA for GovTech suite",
    imageSrc: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg",
    category: "Design",
  },
  {
    id: "des-9",
    name: "Henrik Larson",
    role: "Design Technologist",
    achievement: "Built production prototypes saving $400k in dev",
    imageSrc: "https://images.pexels.com/photos/937481/pexels-photo-937481.jpeg",
    category: "Design",
  },
  {
    id: "des-10",
    name: "Nia Robinson",
    role: "Design Ops Manager",
    achievement: "Scaled Figma org workflow across 200 designers",
    imageSrc: "https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg",
    category: "Design",
  },

  // ==========================================
  // 5. LEADERSHIP (10 Items)
  // ==========================================
  {
    id: "lead-1",
    name: "Arthur Pendelton",
    role: "Former SaaS CEO",
    achievement: "Led company through $450M public exit",
    imageSrc: "https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg",
    category: "Leadership",
  },
  {
    id: "lead-2",
    name: "Helena Rostova",
    role: "Chief Operating Officer",
    achievement: "Scaled operations across 14 international offices",
    imageSrc: "https://images.pexels.com/photos/762020/pexels-photo-762020.jpeg",
    category: "Leadership",
  },
  {
    id: "lead-3",
    name: "Kwame Asante",
    role: "Venture Partner & Board Advisor",
    achievement: "Advised 30+ Series A & B tech founders",
    imageSrc: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg",
    category: "Leadership",
  },
  {
    id: "lead-4",
    name: "Brigitte Weber",
    role: "VP of People & Culture",
    achievement: "Built remote-first culture retained at 94%",
    imageSrc: "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg",
    category: "Leadership",
  },
  {
    id: "lead-5",
    name: "Gabriel Santos",
    role: "Executive Coach & Ex-CTO",
    achievement: "Coached 150+ VP-level technical leaders",
    imageSrc: "https://images.pexels.com/photos/1516680/pexels-photo-1516680.jpeg",
    category: "Leadership",
  },
  {
    id: "lead-6",
    name: "Margaret Campbell",
    role: "General Manager",
    achievement: "Grew enterprise business unit from $10M to $120M",
    imageSrc: "https://images.pexels.com/photos/3777943/pexels-photo-3777943.jpeg",
    category: "Leadership",
  },
  {
    id: "lead-7",
    name: "Deepak Choudhury",
    role: "VP of Engineering Leadership",
    achievement: "Scaled engineering org from 15 to 400 engineers",
    imageSrc: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg",
    category: "Leadership",
  },
  {
    id: "lead-8",
    name: "Claire Boucher",
    role: "Strategic Finance Director",
    achievement: "Structured $75M debt & equity funding rounds",
    imageSrc: "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg",
    category: "Leadership",
  },
  {
    id: "lead-9",
    name: "Tariq Mansour",
    role: "Chief Product & Tech Officer",
    achievement: "Built and integrated 3 acquired tech stacks",
    imageSrc: "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg",
    category: "Leadership",
  },
  {
    id: "lead-10",
    name: "Valeria Rossi",
    role: "Crisis & Change Management Partner",
    achievement: "Turnaround advisor for distressed unicorns",
    imageSrc: "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg",
    category: "Leadership",
  },

  // ==========================================
  // 6. MARKETING (10 Items)
  // ==========================================
  {
    id: "mkt-1",
    name: "Elena Rostova",
    role: "Head of Marketing",
    achievement: "10x organic growth in 1 yr",
    imageSrc: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg",
    category: "Marketing",
  },
  {
    id: "mkt-2",
    name: "Jack Callahan",
    role: "Performance Marketing Lead",
    achievement: "Managed $15M+ annual paid media spend at 4x ROAS",
    imageSrc: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg",
    category: "Marketing",
  },
  {
    id: "mkt-3",
    name: "Pooja Malhotra",
    role: "Product Marketing Director",
    achievement: "Spearheaded GTM strategy for 4 Tier-1 launches",
    imageSrc: "https://images.pexels.com/photos/1820559/pexels-photo-1820559.jpeg",
    category: "Marketing",
  },
  {
    id: "mkt-4",
    name: "Ethan Wright",
    role: "SEO & Organic Acquisition Lead",
    achievement: "Generated 35M monthly organic search visits",
    imageSrc: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg",
    category: "Marketing",
  },
  {
    id: "mkt-5",
    name: "Simona Castelli",
    role: "Lifecycle Marketing Lead",
    achievement: "Lifted email retention revenue by 48%",
    imageSrc: "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg",
    category: "Marketing",
  },
  {
    id: "mkt-6",
    name: "Brendan Cole",
    role: "Content Strategy Director",
    achievement: "Scaled B2B newsletter to 500k subscribers",
    imageSrc: "https://images.pexels.com/photos/837358/pexels-photo-837358.jpeg",
    category: "Marketing",
  },
  {
    id: "mkt-7",
    name: "Naomi Takahashi",
    role: "Brand Communications VP",
    achievement: "Earned Tier 1 press in WSJ, Forbes & Bloomberg",
    imageSrc: "https://images.pexels.com/photos/3756679/pexels-photo-3756679.jpeg",
    category: "Marketing",
  },
  {
    id: "mkt-8",
    name: "Lucas Althaus",
    role: "Developer Relations & Marketing Lead",
    achievement: "Built developer community from 0 to 80K active devs",
    imageSrc: "https://images.pexels.com/photos/1680172/pexels-photo-1680172.jpeg",
    category: "Marketing",
  },
  {
    id: "mkt-9",
    name: "Zainab Badawi",
    role: "Influencer & Social Marketing Head",
    achievement: "Produced viral campaigns generating 200M+ views",
    imageSrc: "https://images.pexels.com/photos/1181519/pexels-photo-1181519.jpeg",
    category: "Marketing",
  },
  {
    id: "mkt-10",
    name: "Harrison Lee",
    role: "RevOps & Attribution Architect",
    achievement: "Standardized multi-touch attribution model",
    imageSrc: "https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg",
    category: "Marketing",
  },
];